### PR TITLE
Add and default debug suffixes to static lib build. Fix static suffix…

### PR DESCRIPTION
**Pull request by watsontandrew**
Fix debug lib names

### CODE REVIEW

**Comment by radicaljims** [comment]
Just a reminder to me or Justin that we'll need to do the following:

1. Bump `Envision_depends` to reference this commit
2. Modify the `Envision_depends` hash we checkout in the dockerfile for Envision
3. Modify the `Envision_depends` hash we reference in the `build_windows.bat` script
4. Checkout the corresponding `Envision_depends` on the Windows VMs

**Review by radicaljims — APPROVED** [review]

**Comment by radicaljims** [comment]
Are we intending this to supersede this: https://github.com/luminartech/jsoncpp/pull/2/?

**Comment by watsontandrew** [comment]
> Are we intending this to supersede this: #2?

oh I just noticed drew had a PR up for this. I think both achieve the same effect, but I also fixed another issue with the static_suffix not being properly applied.

**Comment by watsontandrew** [comment]
additionally, I have a change up for envision depends which will actually leverage this PR and will link to the debug builds of jsoncpp when appropriate.

**Comment by watsontandrew** [comment]
We will simply use Drew's to fix this:
https://github.com/luminartech/jsoncpp/pull/2

**Pull request closed without merging**
